



#
spring:
  thymeleaf:
    # 关闭缓存
    cache: false

  # 数据源连接
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver





