



#
spring:
  thymeleaf:
    # 关闭缓存
    cache: false

  # 数据源连接
  datasource:
    url: jdbc:mysql://localhost:3306/markdown?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  # encoding
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true





mdFilePath: D:/tmp/