



#
spring:
  thymeleaf:
    # 关闭缓存
    cache: false

  # 数据源连接
  datasource:
    url: jdbc:mysql://localhost:3306/markdown?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  # encoding
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true

#
kisso:
  config:
    sign-key: 9t0pwxGqQSkAb2JCs9Gd7n+dI5+A42iymo1C02r9C2RGiKStYln/IK2GkI/q0/gtoBouW80pJQNaSH6Tk2SFIQ==
    cookie-name: kisso
    login-url: http://127.0.0.1:58080/login


mdFilePath: D:/tmp/