spring:
  profiles:
#    active: dev
    active: pro


  # 上传文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    session:
      timeout: 30m



